services:
  influxdb:
    image: influxdb
    container_name: influxdb
    restart: always
    environment:
      - INFLUXDB_DB=influx
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
    ports:
      - '8086:8086'
    volumes:
      - influxdb_data:/var/lib/influxdb

  telegraf:
    image: telegraf
    container_name: telegraf
    restart: always
    env_file: .env
    volumes:
    - ./data/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb
    links:
      - influxdb
    ports:
    - '8125:8125'

  grafana:
    image: grafana/grafana
    container_name: grafana-server
    restart: always
    depends_on:
      - influxdb
    env_file: .env
    links:
      - influxdb
    ports:
      - '3000:3000'
    volumes:
      - grafana_data:/var/lib/grafana
      - ./data/grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/main.yaml
      - ./data/grafana/datasources:/etc/grafana/provisioning/datasources
      - ./data/grafana/dashboards:/var/lib/grafana/dashboards

  node-red:
    image: nodered/node-red:latest
    container_name: node-red
    restart: always
    volumes:
      - ./data/node-red:/data
    ports:
      - '1880:1880'

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    restart: always
    volumes:
      - ./data/mosquitto/config:/mosquitto/config
      - ./data/mosquitto/data:/mosquitto/data
      - ./data/mosquitto/log:/mosquitto/log
    ports:
      - '1883:1883'

volumes:
  grafana_data: {}
  influxdb_data: {}
