{
 "title": "Feed my plant",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "query0", "query": { "query": "" } }
  ]
 },
 "panels": [
  { "title": "TEMP/HUM/PRESS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "mqtt_consumer",
     "query": "from(bucket: \"feed_my_plant\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"topic\"] == \"feed_my_plant/bme_readings/temp\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      {
       "key": "topic::tag",
       "operator": "=",
       "value": "feed_my_plant/bme_readings/temp"
      }
     ]
    }
   ]
  },
  {
   "title": "Average temperature",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "10m" ], "type": "time" }
     ],
     "measurement": "mqtt_consumer",
     "query": "from(bucket: \"feed_my_plant\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"topic\"] == \"feed_my_plant/bme_readings/temp\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "topic::tag",
       "operator": "=",
       "value": "feed_my_plant/bme_readings/temp"
      }
     ]
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "mqtt_consumer",
     "query": "from(bucket: \"feed_my_plant\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"topic\"] == \"feed_my_plant/bme_readings/hum\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "topic::tag", "operator": "=", "value": "feed_my_plant/bme_readings/hum" }
     ]
    }
   ]
  },
  {
   "title": "Average humidity",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "10m" ], "type": "time" }
     ],
     "measurement": "mqtt_consumer",
     "query": "from(bucket: \"feed_my_plant\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"topic\"] == \"feed_my_plant/bme_readings/hum\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "topic::tag", "operator": "=", "value": "feed_my_plant/bme_readings/hum" }
     ]
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "pressurepa" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "mqtt_consumer",
     "query": "from(bucket: \"feed_my_plant\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"topic\"] == \"feed_my_plant/bme_readings/press\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      {
       "key": "topic::tag",
       "operator": "=",
       "value": "feed_my_plant/bme_readings/press"
      }
     ]
    }
   ]
  },
  {
   "title": "Average pressure",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "10m" ], "type": "time" }
     ],
     "measurement": "mqtt_consumer",
     "query": "from(bucket: \"feed_my_plant\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"topic\"] == \"feed_my_plant/bme_readings/press\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "topic::tag",
       "operator": "=",
       "value": "feed_my_plant/bme_readings/press"
      }
     ]
    }
   ]
  },
  {
   "title": "Relay",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Relay",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "measurement": "mqtt_consumer",
       "query": "from(bucket: \"feed_my_plant\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"topic\"] == \"feed_my_plant/relay\")",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "topic::tag", "operator": "=", "value": "feed_my_plant/relay" }
       ]
      }
     ]
    },
    {
     "title": "Rain",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "measurement": "mqtt_consumer",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "topic::tag", "operator": "=", "value": "feed_my_plant/rain" }
       ]
      }
     ]
    },
    {
     "title": "Panel Title",
     "type": "barchart",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
     "targets": [
      {
       "measurement": "mqtt_consumer",
       "query": "from(bucket: \"feed_my_plant\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"topic\"] == \"feed_my_plant/relay\")",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "topic::tag", "operator": "=", "value": "feed_my_plant/relay" }
       ]
      }
     ]
    }
   ]
  }
 ]
}